# This is a basic workflow to help you get started with Actions

name: Cloudhub2.0 CI/CD Pipeline 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:         
      build:
        runs-on: windows-latest
        steps:
          - name: Checkout this repo
            uses: actions/checkout@v4
    
          - name: Cache dependencies
            uses: actions/cache@v4
            with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-maven-
    
          - name: Set up JDK 1.8
            uses: actions/setup-java@v4
            with:
              distribution: "zulu"
              java-version: 8
          
          - name: Publish to Exchange
            run: |
              mvn deploy --settings .maven/settings.xml  -Dclient.id=38fadeee5b6e4b9eade138b6a3a7dc75 -Dclient.secret=B02E9EBBD9fE4C72aBa32fA9eB6fc591
          - name: Deploy to CloudHub 2.0
            run: |
              mvn deploy --settings .maven/settings.xml  -DmuleDeploy -Dclient.id=38fadeee5b6e4b9eade138b6a3a7dc75 -Dclient.secret=B02E9EBBD9fE4C72aBa32fA9eB6fc591 

     
